// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonInfo.API.DbContexts;

#nullable disable

namespace PokemonInfo.API.Migrations
{
    [DbContext(typeof(PokemonInfoContext))]
    [Migration("20220715155445_SecondSeedingMigration")]
    partial class SecondSeedingMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokemonInfo.API.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("integer");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Hp")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpAtk")
                        .HasColumnType("integer");

                    b.Property<int>("SpDef")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 49,
                            Defense = 49,
                            Description = "Seed Dino",
                            Hp = 45,
                            Name = "Bulbasaur",
                            PrimaryType = "grass",
                            SecondaryType = "poison",
                            SpAtk = 65,
                            SpDef = 65,
                            Speed = 45
                        },
                        new
                        {
                            Id = 2,
                            Attack = 62,
                            Defense = 63,
                            Description = "Seed Dino",
                            Hp = 60,
                            Name = "Ivysaur",
                            PrimaryType = "grass",
                            SecondaryType = "poison",
                            SpAtk = 80,
                            SpDef = 80,
                            Speed = 60
                        },
                        new
                        {
                            Id = 3,
                            Attack = 82,
                            Defense = 83,
                            Description = "Final Seed Dinosaur",
                            Hp = 80,
                            Name = "Venusaur",
                            PrimaryType = "grass",
                            SecondaryType = "poison",
                            SpAtk = 100,
                            SpDef = 100,
                            Speed = 80
                        },
                        new
                        {
                            Id = 4,
                            Attack = 52,
                            Defense = 43,
                            Description = "Fire lizard",
                            Hp = 39,
                            Name = "Charmander",
                            PrimaryType = "fire",
                            SecondaryType = "",
                            SpAtk = 60,
                            SpDef = 50,
                            Speed = 65
                        },
                        new
                        {
                            Id = 5,
                            Attack = 64,
                            Defense = 58,
                            Description = "Next fire lizard",
                            Hp = 58,
                            Name = "Charmeleon",
                            PrimaryType = "fire",
                            SecondaryType = "",
                            SpAtk = 80,
                            SpDef = 65,
                            Speed = 80
                        },
                        new
                        {
                            Id = 6,
                            Attack = 84,
                            Defense = 78,
                            Description = "Biggest fire lizard",
                            Hp = 78,
                            Name = "Charizard",
                            PrimaryType = "fire",
                            SecondaryType = "flying",
                            SpAtk = 109,
                            SpDef = 85,
                            Speed = 100
                        },
                        new
                        {
                            Id = 7,
                            Attack = 48,
                            Defense = 65,
                            Description = "Small turtle",
                            Hp = 44,
                            Name = "Squirtle",
                            PrimaryType = "water",
                            SecondaryType = "",
                            SpAtk = 50,
                            SpDef = 64,
                            Speed = 43
                        },
                        new
                        {
                            Id = 8,
                            Attack = 63,
                            Defense = 80,
                            Description = "medium turtle",
                            Hp = 59,
                            Name = "Wartortle",
                            PrimaryType = "water",
                            SecondaryType = "",
                            SpAtk = 65,
                            SpDef = 80,
                            Speed = 58
                        },
                        new
                        {
                            Id = 9,
                            Attack = 83,
                            Defense = 100,
                            Description = "Hydropower turtle",
                            Hp = 79,
                            Name = "Blastoise",
                            PrimaryType = "water",
                            SecondaryType = "",
                            SpAtk = 85,
                            SpDef = 105,
                            Speed = 78
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
